'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ic=n=>`<svg class="icon" aria-hidden="true"><use href="#i-${n}"/></svg>`;
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const uid=p=>p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);
const clone=x=>structuredClone(x),now=()=>new Date().toISOString();
const stamp=t=>new Date(t).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
const SCHEMA='autoplan.p3.canvas-prototype/3.0';
let state={schema:SCHEMA,projects:[]},db=null,persistTimer=null,activeId=null,activeFloor='F01',screen='home',tool='select',showOverlay=true;
let view={s:1,x:0,y:0},size={w:0,h:0},image=null,images=new Map(),selected=null,draft=null,draftOriginal=null,drawer=null,modalFocus=null,popFocus=null;
let gesture=null,space=false,paintQueued=false,loadSeq=0,job=null,jobTimer=null,taskExpanded=true,modelOpen=false,modelYaw=-.70,modelPitch=.72,modelExplode=false,modelDrag=null,uploadTarget=null;
const p=()=>state.projects.find(x=>x.id===activeId),head=(pr=p())=>pr?.versions.at(-1),floor=()=>head()?.floors[activeFloor],asset=()=>p()?.assets[floor()?.assetId];
const allItems=(pr=p())=>Object.entries(head(pr)?.floors||{}).flatMap(([fid,f])=>f.items.map(item=>({...item,floorId:fid})));
const limits={file:12*1024*1024,pixels:12_000_000,projects:12,floors:12,versions:100,objects:200,events:1000};
function toast(text,warn=false){const n=document.createElement('div');n.className='toast'+(warn?' warn':'');n.textContent=text;$('toasts').append(n);setTimeout(()=>n.remove(),4500)}
function event(pr,type,text,detail={}){pr.events.push({id:uid('event'),time:now(),type,text,detail});if(pr.events.length>limits.events)pr.events.shift();saveSoon()}
async function img(url){if(images.has(url))return images.get(url);const task=new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('图片读取失败'));im.src=url});images.set(url,task);return task}
function synthetic(f){const names=f===2?['楼梯 A','男卫','管井','通信机房','监控室','女卫','技术办公','资料室','会议室','控制室','检修间','设备支持','开放办公','通信机柜','值班室','楼梯 B']:['楼梯 A','男卫','管井','设备机房','办公室','女卫','资料室','洽谈室','会议室','办公室','档案室','设备支持','综合办公','办公室','休息室','楼梯 B'];const cells=[[64,34,150,111],[229,34,146,111],[390,34,146,111],[555,34,144,111],[64,164,150,50],[229,164,146,50],[390,164,146,50],[555,164,144,50],[64,296,150,50],[229,296,146,50],[390,296,146,50],[555,296,144,50],[64,365,150,111],[229,365,146,111],[390,365,146,111],[555,365,144,111]];let s=`<svg xmlns="http://www.w3.org/2000/svg" width="768" height="512" viewBox="0 0 768 512"><rect width="768" height="512" fill="white"/><rect x="60" y="30" width="648" height="454" fill="#eef4f6" stroke="#1e394c" stroke-width="4"/><rect x="63" y="224" width="642" height="64" fill="white"/>`;cells.forEach((r,i)=>{s+=`<rect x="${r[0]-3}" y="${r[1]-5}" width="${r[2]+12}" height="${r[3]+12}" fill="none" stroke="#335268" stroke-width="2"/>`;if(i===0||i===15){for(let j=0;j<13;j++)s+=`<path d="M ${r[0]+23} ${r[1]+15+j*5}h90" stroke="#7695a5" stroke-width=".8"/>`;s+=`<path d="M${r[0]+66} ${r[1]+13}v73" stroke="#638998"/>`}else if(r[3]>100){for(let j=0;j<3;j++)s+=`<rect x="${r[0]+13+j*41}" y="${r[1]+13}" width="25" height="65" fill="#fafdfb" stroke="#91a7b1"/>`}else{s+=`<rect x="${r[0]+22}" y="${r[1]+10}" width="90" height="10" fill="white" stroke="#91a7b1"/><rect x="${r[0]+33}" y="${r[1]+26}" width="21" height="9" fill="white" stroke="#91a7b1"/>`}let cy=r[1]+(r[3]>100?63:31);s+=`<rect x="${r[0]+r[2]/2-40}" y="${cy-10}" width="80" height="20" fill="white" opacity=".95"/><text x="${r[0]+r[2]/2}" y="${cy+4}" text-anchor="middle" font-family="sans-serif" font-size="12" fill="#324f62">${names[i]}</text>`;if(i<8)s+=`<path d="M${r[0]+35} ${r[1]+r[3]+7}h28" stroke="white" stroke-width="5"/>`;else s+=`<path d="M${r[0]+35} ${r[1]-5}h28" stroke="white" stroke-width="5"/>`});[139,301,465,627].forEach(x=>s+=`<text x="${x}" y="259" text-anchor="middle" font-family="sans-serif" font-size="12" fill="#456072">公共走廊</text>`);s+='</svg>';return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(s)}
function presetItems(f){return [
{id:'ST-A',type:'楼梯',label:'楼梯 A',note:'请复核梯段范围。此框为人工预设候选，不含模型置信度。',rect:[73,46,131,96],source:'preset',status:'pending'},
{id:'EQ-01',type:'机房',label:f===1?'辅助机房':f===2?'通信机房':'设备机房',note:'示例中的功能区域。',rect:[557,40,140,102],source:'preset',status:'candidate'},
{id:'WC-01',type:'卫生间',label:'女卫',note:'功能区预设框。',rect:[231,164,143,50],source:'preset',status:'candidate'},
{id:'RM-01',type:'办公室',label:f===2?'控制室':'办公室',note:'只框定图上证据，不移动墙体。',rect:[232,297,141,48],source:'preset',status:'candidate'},
{id:'EQ-02',type:f===1?'机柜区':'办公室',label:f===1?'机柜区':f===2?'通信机柜':'办公室',note:'可点击修正类别、名称或框范围。',rect:[232,369,140,99],source:'preset',status:'candidate'},
{id:'ST-B',type:'楼梯',label:'楼梯 B',note:'独立的楼梯示意范围，不代表已完成跨层对齐。',rect:[559,371,138,99],source:'preset',status:'candidate'}]}
function createProject(name,sample=false,variant=0){const pr={id:uid('project'),name,sample,assets:{},versions:[],events:[],runs:[],results:[],undo:[],redo:[],currentFloor:'F01',created:now(),updated:now()};const floors={};if(sample){for(let i=1;i<=(variant?2:3);i++){const aid='asset'+i;pr.assets[aid]={id:aid,name:i===1&&!variant?'P2 示例预览.webp':`程序绘制_${i}F_演示.svg`,url:i===1&&!variant?SAMPLE_URL:synthetic(i===1?2:i),width:768,height:512,sample:true,provenance:i===1&&!variant?'来自用户提供的 P2 图的同尺寸压缩预览；1F 仅为演示分配':'程序绘制的楼层演示图，非用户实际楼层图'};floors['F0'+i]={label:i+'F',name:['设备与运维','控制与技术','办公与支持'][i-1],assetId:aid,items:variant?[]:presetItems(i)}}}pr.versions.push({id:'r0',parent:null,title:sample?'导入演示图纸':'创建空项目',created:now(),floors});event(pr,'project.created','创建'+(sample?'演示':'空')+'项目',{sample,modelExecuted:false});return pr}
function seed(){state.projects=[createProject('发电厂辅助用房',true),createProject('运行管理附楼',true,1),createProject('新建重建项目')];saveSoon()}
async function openDB(){return new Promise((resolve,reject)=>{try{const req=indexedDB.open('AutoPlanP3CanvasV3',1);req.onupgradeneeded=()=>req.result.createObjectStore('workspaces');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)}catch(e){reject(e)}})}
function saveSoon(){clearTimeout(persistTimer);if($('saveStatus'))$('saveStatus').textContent=db?'保存中…':'临时会话';persistTimer=setTimeout(persist,170)}
async function persist(){if(!db){$('saveStatus').textContent='临时会话 · 可导出';return}try{const snap=clone(state);await new Promise((resolve,reject)=>{const tx=db.transaction('workspaces','readwrite');tx.objectStore('workspaces').put(snap,'state');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});$('saveStatus').textContent='已保存到本浏览器'}catch(e){$('saveStatus').textContent='保存失败 · 请导出';toast('浏览器保存失败，请通过更多菜单导出工程备份。',true)}}
function download(blob,name){const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000)}
function exportProject(){if(!p())return;download(new Blob([JSON.stringify({schema:SCHEMA,exported:now(),purpose:'INTERACTION_ONLY',modelExecuted:false,project:p()},null,2)],{type:'application/json;charset=utf-8'}),'P3_标注工程_'+head().id+'.json');toast('已导出标注工程；包含本地图片，请妥善保存。')}

async function importProject(file){if(job)return;try{if(file.size>40*1024*1024)throw new Error('工程文件超过 40 MB');if(state.projects.length>=limits.projects)throw new Error('项目数量已达上限');const data=JSON.parse(await file.text()),pr=data.project;if(data.schema!==SCHEMA||data.modelExecuted!==false||!pr||!Array.isArray(pr.versions)||!pr.versions.length||pr.versions.length>limits.versions||!pr.assets||Array.isArray(pr.assets))throw new Error('不是本原型支持的标注工程');const validKey=k=>typeof k==='string'&&/^[a-zA-Z0-9_-]{1,100}$/.test(k)&&!['__proto__','constructor','prototype'].includes(k);if(typeof pr.name!=='string'||pr.name.length>80)throw new Error('项目名称无效');const safeSVG=[synthetic(2),synthetic(3)];let count=0;for(const [id,a] of Object.entries(pr.assets)){if(!validKey(id)||++count>100||typeof a.url!=='string'||a.url.length>18*1024*1024||(!/^data:image\/(png|jpeg|webp);base64,/.test(a.url)&&!safeSVG.includes(a.url)))throw new Error('工程含不允许的图片引用');const im=await img(a.url);if(im.naturalWidth!==a.width||im.naturalHeight!==a.height||a.width*a.height>limits.pixels)throw new Error('图片尺寸不一致');a.sample=a.url===SAMPLE_URL||safeSVG.includes(a.url);if(typeof a.name!=='string'||a.name.length>200)throw new Error('图片名称无效')}
for(let i=0;i<pr.versions.length;i++){const r=pr.versions[i];if(r.id!=='r'+i||r.parent!==(i?'r'+(i-1):null)||typeof r.title!=='string'||r.title.length>200||!r.floors||Object.keys(r.floors).length>limits.floors)throw new Error('版本链不完整');if(r.restoredFrom&&!pr.versions.slice(0,i).some(v=>v.id===r.restoredFrom))throw new Error('恢复来源不存在');for(const [fid,f] of Object.entries(r.floors)){if(!validKey(fid)||!validKey(f.assetId)||!pr.assets[f.assetId]||typeof f.label!=='string'||f.label.length>20||typeof f.name!=='string'||f.name.length>80||!Array.isArray(f.items)||f.items.length>limits.objects)throw new Error('楼层数据无效');const seen=new Set(),a=pr.assets[f.assetId];for(const o of f.items){if(!validKey(o.id)||seen.has(o.id)||!['manual','preset'].includes(o.source)||!['pending','candidate','confirmed'].includes(o.status)||!['type','label','note'].every(k=>typeof o[k]==='string'&&o[k].length<=500)||!Array.isArray(o.rect)||o.rect.length!==4||!o.rect.every(Number.isFinite))throw new Error('标注格式无效');seen.add(o.id);const [x,y,w,h]=o.rect;if(x<0||y<0||w<8||h<8||x+w>a.width+.1||y+h>a.height+.1)throw new Error('标注越界')}}}
pr.id=uid('imported');pr.name=pr.name.slice(0,72)+'（导入）';pr.sample=Object.values(pr.assets).length>0&&Object.values(pr.assets).every(a=>a.sample);pr.currentFloor=Object.keys(pr.versions.at(-1).floors)[0]||'F01';pr.undo=[];pr.redo=[];pr.runs=[];pr.results=[];pr.events=(Array.isArray(pr.events)?pr.events:[]).filter(e=>e&&typeof e.type==='string'&&typeof e.text==='string'&&e.text.length<500&&Number.isFinite(Date.parse(e.time))).slice(-500);state.projects.unshift(pr);event(pr,'project.imported','导入工程为独立项目',{modelExecuted:false,importedVersions:pr.versions.length,resultsNotTrusted:true});saveSoon();enterProject(pr.id);toast('工程已恢复为独立项目。旧项目未覆盖，未沿用结果审批。')}catch(e){toast('工程导入失败：'+e.message,true)}}
