function renderHome(){const q=$('projectSearch').value.trim().toLowerCase();$('projectCount').textContent=state.projects.length;const matches=state.projects.filter(pr=>pr.name.toLowerCase().includes(q));$('projectGrid').innerHTML=matches.map(pr=>{const h=head(pr),fs=Object.values(h.floors),im=pr.assets[fs[0]?.assetId],running=job?.projectId===pr.id;const pending=allItems(pr).filter(x=>x.status==='pending').length;return `<button class="project-card" data-project="${pr.id}"><div class="project-preview ${!im?'empty':''}">${im?`<img src="${im.url}" alt="${esc(pr.name)}图纸缩略图">`:`<div>${ic('upload')}</div>`}</div><span class="project-pill">${pr.sample?'演示项目':'本地项目'}</span><div class="project-info"><h3>${esc(pr.name)}</h3><p>${fs.length?`${fs.length} 个${pr.sample?'演示':''}楼层 · `:''}${h.id} · ${im?esc(im.name):'尚未导入图纸'}</p><div class="project-foot"><span>${running?'流程演示中':pending?pending+' 处待复核':im?'可进入复核':'等待导入'}</span><span class="go">${im?'继续项目':'开始整理'} ${ic('arrow')}</span></div></div></button>`}).join('')||'<div class="empty-search">没有找到对应项目。换个关键词试试。</div>';$('projectGrid').querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>enterProject(b.dataset.project))}
function isDirty(){return !!draft&&(!draftOriginal||JSON.stringify(draft)!==JSON.stringify(draftOriginal))}
function guardDraft(action){if(!draft||!isDirty()){if(draft)cancelDraft(false);action();return}modal('尚有未保存的标注','先保存或放弃，再离开当前操作。',`<p class="small muted">${draftOriginal?'当前对象的编辑':'刚画出的新框'}尚未保存。原图和已保存版本都不受影响。</p>`,`<button class="btn" data-close>继续编辑</button><button class="btn danger" id="discardDraft">放弃草稿</button>`);$('discardDraft').onclick=()=>{closeModal();cancelDraft(false);action()}}
async function enterProject(id){guardDraft(async()=>{activeId=id;screen='workspace';tool='select';document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool==='select'));activeFloor=p().currentFloor||Object.keys(head().floors)[0]||'F01';selected=null;drawer=null;modelOpen=false;closePop();$('home').classList.add('hidden');$('workspace').classList.remove('hidden');$('sideDrawer').classList.add('hidden');$('modelArea').classList.add('hidden');$('resultRibbon').classList.add('hidden');updateUI();await loadFloor(true);renderTask();event(p(),'project.opened','进入工作台',{revision:head().id})})}
function goHome(){guardDraft(()=>{closePop();activeId=null;screen='home';selected=null;drawer=null;$('workspace').classList.add('hidden');$('home').classList.remove('hidden');renderHome();window.scrollTo(0,0)})}
async function loadFloor(fit=true){const seq=++loadSeq;const a=asset();image=null;selected=null;cancelDraft(false);if(a){try{const im=await img(a.url);if(seq!==loadSeq)return;image=im}catch(e){toast(e.message,true)}}updateUI();resize();if(fit)fitView();drawModel()}
function switchFloor(fid){if(fid===activeFloor)return;guardDraft(async()=>{activeFloor=fid;p().currentFloor=fid;closePop();await loadFloor(true);if(drawer)renderDrawer();event(p(),'floor.selected','切换楼层',{floor:fid})})}
function color(o){return o.source==='manual'?'#537da9':o.status==='pending'?'#bb8540':o.status==='confirmed'?'#268767':'#479481'}
function updateUI(){if(!p())return;const a=asset(),f=floor(),pr=p(),h=head();$('projectName').textContent=pr.name;$('floorName').textContent=f?.label||'图纸';$('floorDesc').textContent=f?.name||'未导入';$('revisionLabel').textContent=h.id;$('sourceCaption').textContent=a?'原图 · '+a.name:'待导入图纸';$('sourceFlag').textContent=a?.sample?(a.name.startsWith('P2')?'P2 参考图':'程序绘制'):'本地文件';$('imageSize').textContent=a?`${a.width} × ${a.height} px`:'';$('emptyCanvas').classList.toggle('hidden',!!a);document.querySelector('.floating-tools').classList.toggle('hidden',!a);$('objectSummary').textContent=f?`${f.items.length} 个框`:'未导入';const n=allItems().filter(o=>o.status==='pending').length;$('issuesLabel').textContent=n?`${n} 处待复核`:'对象清单';$('issuesBtn').classList.toggle('issue-trigger',n>0);$('undoBtn').disabled=!pr.undo.length||!!job;$('redoBtn').disabled=!pr.redo.length||!!job;$('recognizeBtn').disabled=!a||!!job;$('recognizeBtn').querySelector('span').textContent=a?.sample?'识别演示':'识别服务未连接';$('generateBtn').disabled=!a||!!job;$('generateBtn').querySelector('span').textContent=job?.projectId===pr.id?'查看演示进度':'生成图纸与模型';if(job?.projectId===pr.id)$('generateBtn').disabled=false;$('stepSource').classList.toggle('done',!!a);$('stepReview').classList.toggle('current',!modelOpen);$('stepResult').classList.toggle('current',modelOpen);$('stepReview').classList.toggle('done',modelOpen);$('stepSource').classList.toggle('current',!a);if(drawer)renderDrawer();renderTask();queueDraw()}
function commit(title,modify,meta={}){const pr=p();if(pr.versions.length>=limits.versions){toast('此原型最多保存 100 个版本，请导出后另建项目。',true);return false}const before=head();const next={id:'r'+pr.versions.length,parent:before.id,title,created:now(),floors:clone(before.floors),...meta};modify(next.floors);pr.undo.push(before.id);pr.redo=[];pr.versions.push(next);pr.updated=now();invalidateResult(pr);event(pr,'revision.created',title,{revision:next.id,parent:next.parent,floor:activeFloor,geometryStatus:'IMAGE_ONLY',...meta});updateUI();return true}
function invalidateResult(pr){for(const r of pr.results)if(r.revision!==head(pr).id)r.stale=true;if(pr.id===activeId){$('resultRibbon').classList.add('hidden');if(modelOpen){modelOpen=false;$('modelArea').classList.add('hidden');requestAnimationFrame(()=>fitView())}}}
function restore(targetId,label,mode='history'){const pr=p(),target=pr.versions.find(r=>r.id===targetId);if(!target)return;if(pr.versions.length>=limits.versions){toast('版本数量已达演示上限。',true);return}const old=head();if(mode==='undo'){pr.redo.push(old.id)}else if(mode==='redo'){pr.undo.push(old.id)}else{pr.undo.push(old.id);pr.redo=[]}const next={id:'r'+pr.versions.length,parent:old.id,restoredFrom:targetId,title:label,created:now(),floors:clone(target.floors)};pr.versions.push(next);if(!next.floors[activeFloor])activeFloor=Object.keys(next.floors)[0]||'F01';invalidateResult(pr);event(pr,'revision.restored',label,{revision:next.id,parent:old.id,restoredFrom:targetId});loadFloor(false);toast(label+'；历史版本保留。')}
function undo(){if(job||!p()?.undo.length)return;guardDraft(()=>{const id=p().undo.pop();restore(id,'撤销上次标注操作','undo')})}
function redo(){if(job||!p()?.redo.length)return;guardDraft(()=>{const id=p().redo.pop();restore(id,'重做标注操作','redo')})}
function setTool(t){if(job){toast('演示处理中，标注暂时锁定。',true);return}guardDraft(()=>{tool=t;selected=null;document.querySelectorAll('[data-tool]').forEach(el=>el.classList.toggle('active',el.dataset.tool===t));$('planCanvas').style.cursor=t==='pan'?'grab':t==='rect'?'crosshair':'default';$('canvasHelp').innerHTML=t==='rect'?'<kbd>R</kbd> 拖动补框，松手后填写 <i>·</i> Esc 取消':'<kbd>R</kbd> 拉框补充 <i>·</i> 滚轮缩放 <i>·</i> 空格拖动';queueDraw()})}
function resize(){if(screen!=='workspace')return;const b=$('stage').getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,3);const old={...size};size={w:b.width,h:b.height};const c=$('planCanvas');c.width=Math.round(size.w*dpr);c.height=Math.round(size.h*dpr);if(old.w&&old.h){view.x+=(size.w-old.w)/2;view.y+=(size.h-old.h)/2}queueDraw();positionEditor();resizeModel()}
function fitView(){if(!asset()||size.w<1)return;const a=asset(),marginX=size.w<640?78:170,marginY=size.h<420?90:135;view.s=Math.min((size.w-marginX)/a.width,(size.h-marginY)/a.height,2.1);view.s=Math.max(view.s,.1);view.x=(size.w-asset().width*view.s)/2+(size.w<640?14:10);view.y=(size.h-asset().height*view.s)/2+3;zoomLabel();queueDraw();positionEditor()}
function zoom(f,x=size.w/2,y=size.h/2){if(gesture||!asset())return;const old=view.s;view.s=clamp(view.s*f,.1,6);view.x=x-(x-view.x)*view.s/old;view.y=y-(y-view.y)*view.s/old;zoomLabel();queueDraw();positionEditor()}
function zoomLabel(){$('zoomValue').textContent=Math.round(view.s*100)+'%'}
function point(e){const b=$('planCanvas').getBoundingClientRect();return [(e.clientX-b.left-view.x)/view.s,(e.clientY-b.top-view.y)/view.s]}
