'use strict';

const SCHEMA='autoplan.p2.ui-prototype.v1';
const $=id=>document.getElementById(id);
const icon=(name)=>`<svg class="icon" aria-hidden="true"><use href="#i-${name}"/></svg>`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const now=()=>new Date().toISOString();
const niceTime=t=>new Date(t).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false});
const uid=p=>p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);
const fmt=n=>Number(n).toLocaleString('zh-CN');
let state=null, page='editor', tool='brush', spaceHeld=false, currentStroke=null, dragOrigin=null;
let view={scale:1,x:0,y:0},stageSize={w:0,h:0},images=new Map(),currentImage=null,db=null,persistTimer=null,savingVersion=0;
let maskE=null,maskP=null,maskA=null,maskStats={raw:0,allowed:0,overlap:0,bbox:null,context:null};
let selectedCandidate=null,selectedRevision=null,compareMode='slider',rawMode=false,activeJob=null,modalReturnFocus=null;
let pointerPos=null,drawFrame=0,jobBusy=false,lastLoadedHead=null,resizeObserver=null,storeBusy=false,lastStoredAt=null;
const LIMITS={pixels:6_000_000,file:12*1024*1024,project:40*1024*1024,revisions:24};
const controls=()=>({walls:$('lockWalls').checked,labels:$('lockLabels').checked});
function head(){return state.revisions.find(r=>r.id===state.headId)}
function rev(id){return state.revisions.find(r=>r.id===id)}
function candidate(id=selectedCandidate){return state.attempts.find(a=>a.id===id)}
function createCanvas(w=state.width,h=state.height){const c=document.createElement('canvas');c.width=w;c.height=h;return c}
function imageOf(url){if(images.has(url))return images.get(url);const promise=new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('图片无法读取'));im.src=url;});images.set(url,promise);return promise}
async function sha(value){if(!globalThis.crypto?.subtle)return null;const bytes=typeof value==='string'?new TextEncoder().encode(value):value;const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function addEvent(type,label,detail={},category='request'){const ev={id:'e'+String(state.events.length+1).padStart(3,'0'),time:now(),type,label,category,detail};state.events.push(ev);scheduleSave();return ev}
function toast(text,warn=false){const el=document.createElement('div');el.className='toast'+(warn?' warn':'');el.textContent=text;$('toasts').append(el);setTimeout(()=>el.remove(),4500)}
function banner(text='',type=''){const el=$('editorBanner');el.className='notice-inline'+(type?' '+type:'')+(text?'':' hidden');el.innerHTML=text?icon('info')+'<span>'+esc(text)+'</span>':''}
async function openDB(){return new Promise((resolve,reject)=>{try{const request=indexedDB.open('AutoPlanP2Prototype',1);request.onupgradeneeded=()=>request.result.createObjectStore('sessions');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)}catch(e){reject(e)}})}
async function loadStore(){if(!db)return null;return new Promise((res,rej)=>{const tx=db.transaction('sessions','readonly');const req=tx.objectStore('sessions').get('current');req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)})}
function scheduleSave(){if(!state)return;clearTimeout(persistTimer);$('saveStatus').innerHTML='<span class="dot"></span>正在保存';persistTimer=setTimeout(persist,220)}
async function persist(){if(!state)return;state.draft={commands:state.draft.commands,redo:state.draft.redo,prompt:$('prompt').value,effect:$('demoEffect').value,settings:controls()};if(!db){$('saveStatus').textContent='仅当前页面 · 请导出备份';return}try{const snapshot=structuredClone(state);await new Promise((res,rej)=>{const tx=db.transaction('sessions','readwrite');tx.objectStore('sessions').put(snapshot,'current');tx.oncomplete=res;tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error)});lastStoredAt=now();$('saveStatus').innerHTML='<span class="dot"></span>已保存到本浏览器'}catch(e){$('storageWarning').classList.remove('hidden');$('saveStatus').textContent='保存失败 · 请导出工程'}}
async function freshState(url=SAMPLE_URL,name='发电厂辅助用房',sample=true){const im=await imageOf(url);const c=createCanvas(im.naturalWidth,im.naturalHeight);c.getContext('2d').drawImage(im,0,0);const canonical=c.toDataURL('image/png');const root={id:'r0',parent:null,restoreFrom:null,time:now(),type:'import',title:'导入原始平面图',description:sample?'用户上传图的本地交互演示副本':'导入的外部图片；未识别几何或尺度',image:canonical,imageHash:await sha(c.getContext('2d').getImageData(0,0,c.width,c.height).data),candidateId:null,geometryStatus:'IMAGE_ONLY'};state={schema:SCHEMA,sessionId:uid('session'),projectName:name,width:c.width,height:c.height,isSample:sample,headId:'r0',revisions:[root],attempts:[],events:[],draft:{commands:[],redo:[],prompt:'',effect:'racks',settings:{walls:sample,labels:sample}}};images.set(canonical,Promise.resolve(im));addEvent('session.imported','导入平面图',{size:[c.width,c.height],scale_status:'UNKNOWN',geometry_status:'IMAGE_ONLY',source_pixels_sha256:root.imageHash,backend:'NONE',original_untouched:true},'version');selectedRevision='r0';selectedCandidate=null;currentImage=await imageOf(canonical);lastLoadedHead='r0';applyDraftToUI();fitCanvas();rebuildMasks();updateChrome();scheduleSave()}
function applyDraftToUI(){$('prompt').value=state.draft.prompt||'';$('demoEffect').value=state.draft.effect||'racks';$('lockWalls').checked=!!state.draft.settings?.walls;$('lockLabels').checked=!!state.draft.settings?.labels;$('lockWalls').disabled=!state.isSample;$('lockLabels').disabled=!state.isSample;$('presetButtons').classList.toggle('hidden',!state.isSample);$('projectTitle').textContent=state.projectName;$('sourceTitle').textContent=state.isSample?'上传平面图 · 楼层未确认':'外部图片 · 尺度与楼层待确认';$('sourceSize').textContent=`${state.width} × ${state.height} px`;updatePromptCount()}
function updateChrome(){document.querySelectorAll('[data-head]').forEach(el=>el.textContent=state.headId);$('candidateBadge').textContent=state.attempts.filter(a=>a.status==='ready').length;$('revisionBadge').textContent=state.revisions.length;$('undoVersion').disabled=state.revisions.length<2||jobBusy;updateDraftButtons();if(page==='history')renderHistory();if(page==='audit')renderAudit()}
function updatePromptCount(){$('promptCount').textContent=`${$('prompt').value.length} / 500`;updateDraftButtons()}
function updateDraftButtons(){if(!state)return;const valid=maskStats.allowed>0&&$('prompt').value.trim().length>0;$('previewScope').disabled=!valid||jobBusy;$('undoStroke').disabled=!state.draft.commands.length||jobBusy;$('redoStroke').disabled=!state.draft.redo.length||jobBusy;$('clearMask').disabled=!state.draft.commands.length||jobBusy;$('stageDraft').classList.toggle('hidden',!state.draft.commands.length);$('step1').className='step '+(maskStats.allowed>0?'done':'current');$('step2').className='step '+($('prompt').value.trim()?'done':maskStats.allowed>0?'current':'');$('step3').className='step '+(jobBusy?'current':'');$('step4').className='step '+(state.attempts.some(a=>a.status==='ready')?'current':'')}
function setPage(value){if(currentStroke)endPointer();page=value;document.querySelectorAll('.page').forEach(el=>el.classList.toggle('hidden',el.id!=='page-'+page));document.querySelectorAll('[data-page]').forEach(el=>el.classList.toggle('active',el.dataset.page===page));const labels={editor:'编辑工作台',compare:'候选对比',history:'版本历史',audit:'过程记录',guide:'操作与实现'};$('crumbPage').textContent=labels[page];if(page==='editor'){requestAnimationFrame(()=>{resizeCanvas();draw()})}if(page==='compare')renderCompare();if(page==='history')renderHistory();if(page==='audit')renderAudit();window.scrollTo({top:0,behavior:'instant'})}
function setTool(value){tool=value;document.querySelectorAll('[data-tool]').forEach(el=>el.classList.toggle('active',el.dataset.tool===tool));$('eraseTarget').classList.toggle('hidden',tool!=='erase');updateToolLabel();$('editorCanvas').style.cursor=tool==='pan'?'grab':'crosshair';draw()}
function updateToolLabel(){const names={brush:'画笔',erase:'橡皮',protect:'保护笔',rect:'矩形',pan:'平移'};$('stageTool').textContent=names[tool]+(tool==='brush'||tool==='erase'||tool==='protect'?' / '+$('brushSize').value+' px':'');$('brushValue').textContent=$('brushSize').value+' px'}
function resizeCanvas(){const stage=$('stage');if(!stage.clientWidth)return;const c=$('editorCanvas'),oldW=stageSize.w,oldH=stageSize.h;const w=stage.clientWidth,h=stage.clientHeight,dpr=Math.max(1,window.devicePixelRatio||1);stageSize={w,h};c.width=Math.round(w*dpr);c.height=Math.round(h*dpr);if(oldW&&oldH){view.x+=(w-oldW)/2;view.y+=(h-oldH)/2}else fitCanvas();draw()}
function fitCanvas(){if(!state)return;const w=$('stage').clientWidth||700,h=$('stage').clientHeight||500;view.scale=Math.min((w-48)/state.width,(h-48)/state.height);view.x=(w-state.width*view.scale)/2;view.y=(h-state.height*view.scale)/2;updateZoom();draw()}
function updateZoom(){$('zoomValue').textContent=Math.round(view.scale*100)+'%'}
function zoom(factor,cx=stageSize.w/2,cy=stageSize.h/2){if(currentStroke)return;const prev=view.scale;view.scale=clamp(prev*factor,.15,6);view.x=cx-(cx-view.x)*view.scale/prev;view.y=cy-(cy-view.y)*view.scale/prev;updateZoom();draw()}
function sourcePoint(event){const b=$('editorCanvas').getBoundingClientRect();return [(event.clientX-b.left-view.x)/view.scale,(event.clientY-b.top-view.y)/view.scale]}
function inside(p){return p[0]>=0&&p[1]>=0&&p[0]<state.width&&p[1]<state.height}
function applyCommand(c,command){const ctx=c.getContext('2d');ctx.save();if(command.kind==='clear'){ctx.clearRect(0,0,c.width,c.height);ctx.restore();return}ctx.globalCompositeOperation=command.erase?'destination-out':'source-over';ctx.fillStyle='white';ctx.strokeStyle='white';ctx.lineWidth=command.width;ctx.lineCap='round';ctx.lineJoin='round';if(command.kind==='rect'){const[a,b]=command.points;ctx.fillRect(Math.min(a[0],b[0]),Math.min(a[1],b[1]),Math.abs(b[0]-a[0]),Math.abs(b[1]-a[1]))}else{const pts=command.points;if(pts.length===1){ctx.beginPath();ctx.arc(pts[0][0],pts[0][1],command.width/2,0,Math.PI*2);ctx.fill()}else{ctx.beginPath();ctx.moveTo(...pts[0]);for(let i=1;i<pts.length;i++)ctx.lineTo(...pts[i]);ctx.stroke()}}ctx.restore()}
function drawPresetProtection(c){if(!state.isSample)return;const ctx=c.getContext('2d');ctx.fillStyle='white';if($('lockWalls').checked){[[55,24,12,464],[702,24,12,465],[55,24,660,12],[55,478,660,12],[217,26,11,200],[378,26,13,200],[541,26,12,200],[216,282,13,204],[378,282,13,204],[541,282,13,204],[58,149,651,13],[58,217,651,13],[58,282,651,14],[58,350,651,13],[63,33,154,116],[553,363,147,113],[60,225,647,61],[387,35,153,111]].forEach(r=>ctx.fillRect(...r))}if($('lockLabels').checked){[[142,91,56,20],[303,89,39,19],[465,92,38,20],[626,92,67,20],[142,189,58,20],[303,190,38,20],[465,189,71,20],[626,189,60,20],[142,319,60,21],[303,319,60,20],[465,320,53,20],[626,320,71,20],[142,418,66,20],[303,418,61,20],[465,418,67,20],[626,419,61,20]].forEach(([x,y,w,h])=>ctx.fillRect(x-w/2,y-h/2,w,h))}}
